name: arduino_desktop
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bson:
    git:
      url: git@github.com:mongo-dart/bson.git
      ref: master
  flutter_libserialport:
    git:
      url: git@github.com:jpnurmi/flutter_libserialport.git
      ref: master
  flutter_modular: ^3.0.2+1
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  shared_preferences: ^2.0.5
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/translations/